################################################
# APPLICATION INFO
################################################

spring.application.name=Prismo
application.version=0.0.1-SNAPSHOT
app.environment=DEV

################################################
# SERVER CONFIGURATION
################################################

server.port=${PORT:5000}
server.servlet.context-path=/

################################################
# BANNER CONFIG
################################################

spring.main.banner-mode=console

################################################
# ADMIN DEFAULT CONFIG
################################################

app.admin.username=admin
app.admin.password=admin123
app.admin.role=ROLE_ADMIN

################################################
# LOGGING
################################################

logging.level.root=INFO
logging.level.org.springframework=INFO

################################################
# JVM / PERFORMANCE (optional future tuning)
################################################

spring.output.ansi.enabled=ALWAYS

################################################
# Connection Db Supabase
################################################

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.wvanppmquhwiiucuqquo
spring.datasource.password=${SUPABASE_PASSWORD:s5/VVX/9bz-sT/_}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.auto-commit=true

jwt.secret=${JWT_SECRET:minha-chave-secreta-muito-segura-e-longa-para-jwt-256-bits}
jwt.expiration=86400000

spring.jpa.open-in-view=false



jwt.secret=${JWT_SECRET:minha-chave-secreta-muito-segura-e-longa-para-jwt-256-bits}
jwt.expiration=86400000

spring.jpa.open-in-view=false

