################################################
# APPLICATION INFO
################################################

spring.application.name=Prismo
application.version=0.0.1-SNAPSHOT
app.environment=DEV

################################################
# SERVER CONFIGURATION
################################################

server.port=${PORT:8080}
server.servlet.context-path=/

################################################
# BANNER CONFIG
################################################

spring.main.banner-mode=console

################################################
# ADMIN DEFAULT CONFIG
################################################

app.admin.username=admin
app.admin.password=admin123
app.admin.role=ROLE_ADMIN

################################################
# LOGGING
################################################

logging.level.root=INFO
logging.level.org.springframework=INFO

################################################
# JVM / PERFORMANCE (optional future tuning)
################################################

spring.output.ansi.enabled=ALWAYS

################################################
# Connection Db Supabase
################################################
spring.datasource.url=jdbc:postgresql://db.jkyimbkddsidgahwwkkh.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
